# Generated by Django 3.0.7 on 2020-06-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_name', models.CharField(default='Nothing', max_length=300)),
                ('c_v', models.CharField(default='Nothing', max_length=300)),
                ('bc_fk', models.IntegerField(default=1)),
                ('row_num', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Basedetails',
            },
        ),
    ]
