# Generated by Django 3.0.7 on 2020-06-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_basedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecolumns',
            name='d_size',
            field=models.IntegerField(default=40),
        ),
    ]
