# Generated by Django 3.0.7 on 2020-06-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_basecolumns_d_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='Nothing', max_length=50)),
                ('created_by', models.CharField(default='Nothing', max_length=300)),
            ],
            options={
                'db_table': 'Groupname',
            },
        ),
        migrations.CreateModel(
            name='Usergroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Nothing', max_length=50)),
                ('column_add', models.BooleanField(default=False)),
                ('column_delete', models.BooleanField(default=False)),
                ('column_edit', models.BooleanField(default=False)),
                ('row_add', models.BooleanField(default=False)),
                ('row_edit', models.BooleanField(default=False)),
                ('row_delete', models.BooleanField(default=False)),
                ('column_view', models.BooleanField(default=False)),
                ('row_view', models.BooleanField(default=False)),
                ('truncate_table', models.BooleanField(default=False)),
                ('delete_table', models.BooleanField(default=False)),
                ('base_fk', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Usergroup',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='Nothing', max_length=50)),
                ('fk_groupname', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
