# Generated by Django 3.0.7 on 2020-06-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_groupname_usergroup_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equ', models.CharField(default='Nothing', max_length=500)),
                ('equ_normal', models.CharField(default='Nothing', max_length=500)),
                ('createdby', models.CharField(default='Nothing', max_length=500)),
                ('fk_table', models.IntegerField(default=1)),
                ('fk_column', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Calculation',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nothing', max_length=50)),
                ('lname', models.CharField(default='Nothing', max_length=50)),
                ('phone', models.BigIntegerField(default=0)),
                ('skype', models.CharField(default='Nothing', max_length=50)),
                ('location', models.CharField(default='Nothing', max_length=50)),
                ('user_image', models.FileField(blank=True, upload_to='media')),
                ('log_fk', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
    ]
