# Generated by Django 3.0.7 on 2020-07-09 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_calculation_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='company_name',
            field=models.CharField(default='Unknown', max_length=300),
        ),
        migrations.AddField(
            model_name='login',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='login',
            name='profile',
            field=models.CharField(default='Unknown', max_length=300),
        ),
        migrations.AddField(
            model_name='login',
            name='role',
            field=models.CharField(default='Unknown', max_length=300),
        ),
        migrations.AlterField(
            model_name='login',
            name='phone',
            field=models.CharField(default='0000000000', max_length=50),
        ),
    ]
