# Generated by Django 3.0.7 on 2020-07-09 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_name', models.CharField(default='Nothing', max_length=300)),
                ('base_create_date', models.DateField(default=django.utils.timezone.now)),
                ('base_modified_date', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(default='Nothing', max_length=300)),
                ('technical_name', models.CharField(default='Nothing', max_length=300)),
                ('table_type', models.CharField(default='Nothing', max_length=300)),
                ('discription', models.CharField(default='Nothing', max_length=500)),
                ('purpose', models.CharField(default='Nothing', max_length=400)),
                ('bcp', models.CharField(default='Nothing', max_length=300)),
                ('tags', models.CharField(default='Nothing', max_length=400)),
                ('fk', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Base',
            },
        ),
        migrations.CreateModel(
            name='Basecolumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_name', models.CharField(default='Nothing', max_length=300)),
                ('base_create_date', models.DateField(default=django.utils.timezone.now)),
                ('base_modified_date', models.DateField(default=django.utils.timezone.now)),
                ('c_name', models.CharField(default='Nothing', max_length=300)),
                ('d_type', models.CharField(default='Text', max_length=300)),
                ('d_size', models.IntegerField(default=40)),
                ('base_fk', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Basecolumns',
            },
        ),
        migrations.CreateModel(
            name='Basedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_name', models.CharField(default='Nothing', max_length=300)),
                ('c_v', models.CharField(default='Nothing', max_length=300)),
                ('bc_fk', models.IntegerField(default=1)),
                ('row_num', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Basedetails',
            },
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equ', models.CharField(default='Nothing', max_length=500)),
                ('equ_normal', models.CharField(default='Nothing', max_length=500)),
                ('createdby', models.CharField(default='Nothing', max_length=500)),
                ('fk_table', models.IntegerField(default=1)),
                ('fk_column', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Calculation',
            },
        ),
        migrations.CreateModel(
            name='Groupname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='Nothing', max_length=50)),
                ('created_by', models.CharField(default='Nothing', max_length=300)),
            ],
            options={
                'db_table': 'Groupname',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nothing', max_length=50)),
                ('phone', models.CharField(default='0000000000', max_length=50)),
                ('password', models.CharField(default='Nothing', max_length=50)),
                ('email', models.CharField(default='Nothing', max_length=50)),
                ('is_active', models.CharField(default='Nothing', max_length=50)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('company_name', models.CharField(default='Unknown', max_length=300)),
                ('profile', models.CharField(default='Unknown', max_length=300)),
                ('role', models.CharField(default='Unknown', max_length=300)),
            ],
            options={
                'db_table': 'Login',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nothing', max_length=50)),
                ('lname', models.CharField(default='Nothing', max_length=50)),
                ('phone', models.BigIntegerField(default=0)),
                ('skype', models.CharField(default='Nothing', max_length=50)),
                ('location', models.CharField(default='Nothing', max_length=50)),
                ('user_image', models.FileField(blank=True, upload_to='media')),
                ('log_fk', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Usergroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Nothing', max_length=50)),
                ('column_add', models.BooleanField(default=False)),
                ('column_delete', models.BooleanField(default=False)),
                ('column_edit', models.BooleanField(default=False)),
                ('row_add', models.BooleanField(default=False)),
                ('row_edit', models.BooleanField(default=False)),
                ('row_delete', models.BooleanField(default=False)),
                ('column_view', models.BooleanField(default=False)),
                ('row_view', models.BooleanField(default=False)),
                ('truncate_table', models.BooleanField(default=False)),
                ('delete_table', models.BooleanField(default=False)),
                ('base_fk', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Usergroup',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='Nothing', max_length=50)),
                ('fk_groupname', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
