# Generated by Django 3.0.7 on 2020-07-14 06:14

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification_Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField(default=1)),
                ('reciever_id', models.IntegerField(default=1)),
                ('send_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(default=1)),
                ('heading', models.CharField(default='No Message', max_length=200)),
                ('message', models.CharField(default='No Message', max_length=500)),
                ('link', models.CharField(default='No', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='No', max_length=50)),
                ('profile', models.CharField(default='No', max_length=50)),
                ('admin_id', models.IntegerField(default=1)),
                ('user_id', models.CharField(default='No', max_length=200)),
                ('created_date', models.DateField(default=datetime.date(2020, 7, 14))),
            ],
        ),
    ]
