# Generated by Django 3.0.7 on 2020-07-20 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_notification_messages_user_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_user', models.IntegerField(default=0)),
                ('role', models.CharField(default='None', max_length=200)),
                ('about', models.TextField(default='Describe this Role / Group in few words')),
                ('add_user', models.CharField(default='False', max_length=20)),
                ('create_tables', models.CharField(default='False', max_length=20)),
                ('add_data', models.CharField(default='False', max_length=20)),
                ('delete_data', models.CharField(default='False', max_length=20)),
                ('update_data', models.CharField(default='False', max_length=20)),
                ('add_col', models.CharField(default='False', max_length=20)),
                ('delete_col', models.CharField(default='False', max_length=20)),
                ('update_col', models.CharField(default='False', max_length=20)),
            ],
            options={
                'db_table': 'Permission_tbl',
            },
        ),
        migrations.AddField(
            model_name='user_list',
            name='table_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification_messages',
            name='reciever_id',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 7, 20)),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='role',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='notification_messages',
            table='Notification_tbl',
        ),
        migrations.AlterModelTable(
            name='user_list',
            table='Users_list',
        ),
    ]
