# Generated by Django 3.0.7 on 2020-07-21 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_auto_20200720_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_list',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 7, 21)),
        ),
    ]
