# Generated by Django 3.0.7 on 2020-07-22 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_auto_20200721_1129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groupname',
        ),
        migrations.DeleteModel(
            name='Usergroup',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AlterField(
            model_name='user_list',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 7, 22)),
        ),
    ]
