# Generated by Django 3.0.7 on 2020-07-23 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_auto_20200722_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='disable_period',
            field=models.CharField(default='Unknown', max_length=300),
        ),
        migrations.AddField(
            model_name='login',
            name='is_disabled',
            field=models.CharField(default='Unknown', max_length=300),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 7, 23)),
        ),
    ]
