# Generated by Django 3.0.7 on 2020-07-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_auto_20200730_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecolumns',
            name='calc_type',
            field=models.CharField(default='Nothing', max_length=20),
        ),
        migrations.AlterField(
            model_name='basecolumns',
            name='base_fk',
            field=models.IntegerField(default=0),
        ),
    ]
