# Generated by Django 3.0.7 on 2020-07-31 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_auto_20200730_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdfReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reportname', models.CharField(default='Nothing', max_length=50)),
                ('DetailRname', models.CharField(default='Nothing', max_length=50)),
                ('pdf_path', models.FileField(blank=True, upload_to='media/reports')),
                ('created_date', models.DateField(default=datetime.date(2020, 7, 31))),
                ('created_by', models.CharField(default='Nothing', max_length=300)),
            ],
            options={
                'db_table': 'report_pdf',
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 7, 31)),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 7, 31)),
        ),
    ]
