# Generated by Django 3.0.7 on 2020-08-14 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_auto_20200813_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_model_primary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id_primary', models.IntegerField(default=0)),
                ('tables_name_primary', models.CharField(default='Nothing', max_length=200)),
                ('created_users_id', models.IntegerField(default=0)),
                ('created_users_email', models.CharField(default='Unknown', max_length=300)),
                ('Group_name', models.CharField(default='Nothing', max_length=100)),
            ],
            options={
                'db_table': 'Model_Group_Primary',
            },
        ),
        migrations.CreateModel(
            name='Group_model_secondary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_tables_id', models.CharField(default='[]', max_length=200)),
                ('secondary_tables_name', models.CharField(default='Nothing', max_length=200)),
                ('primary_table_fk', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Model_Group_Secondary',
            },
        ),
        migrations.AlterField(
            model_name='pdfreport',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 8, 14)),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 8, 14)),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 8, 14)),
        ),
    ]
