# Generated by Django 3.0.7 on 2020-08-20 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_auto_20200814_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='create_report',
            field=models.CharField(default='False', max_length=20),
        ),
        migrations.AddField(
            model_name='permissions',
            name='delete_report',
            field=models.CharField(default='False', max_length=20),
        ),
        migrations.AlterField(
            model_name='pdfreport',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 8, 20)),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 8, 20)),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 8, 20)),
        ),
    ]
