# Generated by Django 3.0.7 on 2020-08-21 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0012_auto_20200820_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='view_report',
            field=models.CharField(default='False', max_length=20),
        ),
        migrations.AlterField(
            model_name='pdfreport',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 8, 21)),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 8, 21)),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 8, 21)),
        ),
    ]
