# Generated by Django 3.0.7 on 2020-08-25 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0013_auto_20200821_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_list',
            name='report_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pdfreport',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 8, 25)),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 8, 25)),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 8, 25)),
        ),
    ]
