# Generated by Django 3.0.7 on 2020-08-27 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0014_auto_20200825_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecolumns',
            name='t_name',
            field=models.CharField(default='Nothing', max_length=300),
        ),
        migrations.AlterField(
            model_name='pdfreport',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 8, 27)),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 8, 27)),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 8, 27)),
        ),
    ]
