# Generated by Django 3.0.7 on 2020-09-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0017_auto_20200911_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecolumns',
            name='nul_type',
            field=models.CharField(default='NOTNULL', max_length=300),
        ),
    ]
